### ISSUE TITLE
Jabber protocol

### ISSUE THREAD

**Issue by deavmi** [deavmi/Picy#18]
What is the URI (is that the correct use of the word **URI**?) for jabber clients?

Is it `jabber://` or `xmpp://`?

**Comment by deavmi** [comment]
I'm going to go with `jabber://` for now.

**Comment by deavmi** [comment]
Looks like `xmpp://` works on the Mac. Going to switch to this now.

**Comment by Walkman100** [comment]
@deavmi Yes URI protocol is the correct name

**Comment by Walkman100** [comment]
@deavmi >mac

**Comment by deavmi** [comment]
> ">mac"
?

**Comment by deavmi** [comment]
@Walkman100 Okay. Thanks.

**Comment by deavmi** [comment]
URI **protocol** oh, that makes more sense after reading the Wikipedia page.

**Comment by Walkman100** [comment]
lol that mac comment made more sense in the telegram chat, I've updated it so it makes sense now
